import { Typography } from "@/components/ui/typography";

export function ReportFooter() {
  return (
    <div className="border-t border-border pt-6 text-center">
      <Typography variant="caption" className="text-muted-foreground">
        This report was generated by FuturePath AI based on your child&apos;s assessment responses.
        It is intended to support — not replace — guidance from teachers, counselors, and other
        trusted advisors.
      </Typography>
    </div>
  );
}