import type { SalaryRange } from "@/lib/careers/salary-data";
import type { FutureDemand, AutomationRisk } from "@/lib/careers/demand-data";

export interface CareerRecord {
  id: string;
  name: string;
  category: string;
  description: string;
  averageSalary: SalaryRange;
  requiredDegree: string;
  skills: string[];
  futureDemand: FutureDemand;
  automationRisk: AutomationRisk;
  typicalPersonality: string[];
  workEnvironment: string;
  growthRate: number;
}

const USD = "$";

export const CAREER_DATA: CareerRecord[] = [
  // ---- Technology (8) ----
  { id: "software-engineer", name: "Software Engineer", category: "technology", description: "Designs, builds, and maintains software applications and systems.", averageSalary: { min: 75000, max: 160000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Programming", "Problem solving", "Logical thinking", "Debugging"], futureDemand: "Very High", automationRisk: "Low", typicalPersonality: ["Analytical", "Detail-oriented", "Independent"], workEnvironment: "Office / Remote", growthRate: 25 },
  { id: "data-scientist", name: "Data Scientist", category: "technology", description: "Analyzes complex data to uncover insights and guide business decisions.", averageSalary: { min: 85000, max: 165000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Statistics", "Programming", "Data analysis", "Machine learning"], futureDemand: "Very High", automationRisk: "Low", typicalPersonality: ["Analytical", "Curious", "Methodical"], workEnvironment: "Office / Remote", growthRate: 30 },
  { id: "cybersecurity-analyst", name: "Cybersecurity Analyst", category: "technology", description: "Protects computer systems and networks from digital threats.", averageSalary: { min: 80000, max: 150000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Security analysis", "Attention to detail", "Problem solving", "Networking"], futureDemand: "Very High", automationRisk: "Low", typicalPersonality: ["Vigilant", "Analytical", "Persistent"], workEnvironment: "Office / Remote", growthRate: 32 },
  { id: "cloud-architect", name: "Cloud Solutions Architect", category: "technology", description: "Designs scalable cloud infrastructure for organizations.", averageSalary: { min: 100000, max: 180000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Systems design", "Cloud platforms", "Problem solving", "Communication"], futureDemand: "Very High", automationRisk: "Low", typicalPersonality: ["Strategic", "Analytical", "Organized"], workEnvironment: "Office / Remote", growthRate: 27 },
  { id: "ux-ui-designer", name: "UX/UI Designer", category: "technology", description: "Designs intuitive, user-friendly digital product experiences.", averageSalary: { min: 65000, max: 130000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Design", "Empathy", "Prototyping", "Communication"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Creative", "Empathetic", "Detail-oriented"], workEnvironment: "Office / Remote", growthRate: 18 },
  { id: "mobile-developer", name: "Mobile App Developer", category: "technology", description: "Builds applications for smartphones and tablets.", averageSalary: { min: 70000, max: 145000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Programming", "UI design", "Problem solving", "Testing"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Creative", "Analytical", "Independent"], workEnvironment: "Office / Remote", growthRate: 20 },
  { id: "ml-engineer", name: "AI/Machine Learning Engineer", category: "technology", description: "Builds and deploys machine learning models and AI systems.", averageSalary: { min: 100000, max: 190000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Programming", "Mathematics", "Machine learning", "Research"], futureDemand: "Very High", automationRisk: "Low", typicalPersonality: ["Analytical", "Curious", "Persistent"], workEnvironment: "Office / Remote", growthRate: 35 },
  { id: "devops-engineer", name: "DevOps Engineer", category: "technology", description: "Automates and streamlines software delivery and infrastructure.", averageSalary: { min: 85000, max: 160000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Automation", "Systems administration", "Problem solving", "Collaboration"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Organized", "Analytical", "Collaborative"], workEnvironment: "Office / Remote", growthRate: 22 },

  // ---- Business (7) ----
  { id: "management-consultant", name: "Management Consultant", category: "business", description: "Advises organizations on strategy, operations, and performance improvement.", averageSalary: { min: 80000, max: 170000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analysis", "Communication", "Problem solving", "Strategic thinking"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Confident", "Analytical", "Adaptable"], workEnvironment: "Office / Travel", growthRate: 14 },
  { id: "business-analyst", name: "Business Analyst", category: "business", description: "Bridges business needs and technical solutions within an organization.", averageSalary: { min: 65000, max: 120000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analysis", "Communication", "Documentation", "Problem solving"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Analytical", "Organized", "Communicative"], workEnvironment: "Office / Remote", growthRate: 15 },
  { id: "product-manager", name: "Product Manager", category: "business", description: "Guides product strategy and coordinates teams to build it.", averageSalary: { min: 90000, max: 170000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Leadership", "Strategic thinking", "Communication", "Prioritization"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Decisive", "Collaborative", "Strategic"], workEnvironment: "Office / Remote", growthRate: 19 },
  { id: "operations-manager", name: "Operations Manager", category: "business", description: "Oversees daily operations to ensure efficiency and quality.", averageSalary: { min: 65000, max: 130000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Organization", "Leadership", "Problem solving", "Communication"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Organized", "Practical", "Decisive"], workEnvironment: "Office / On-site", growthRate: 9 },
  { id: "hr-manager", name: "Human Resources Manager", category: "business", description: "Manages recruitment, employee relations, and workplace policy.", averageSalary: { min: 60000, max: 125000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Communication", "Empathy", "Organization", "Conflict resolution"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Empathetic", "Organized", "Diplomatic"], workEnvironment: "Office", growthRate: 8 },
  { id: "supply-chain-manager", name: "Supply Chain Manager", category: "business", description: "Coordinates the flow of goods from suppliers to customers.", averageSalary: { min: 70000, max: 135000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Logistics", "Analysis", "Negotiation", "Organization"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Organized", "Analytical", "Practical"], workEnvironment: "Office / Warehouse", growthRate: 11 },
  { id: "entrepreneur", name: "Entrepreneur / Small Business Owner", category: "business", description: "Builds and runs an independent business venture.", averageSalary: { min: 30000, max: 250000, currency: USD }, requiredDegree: "Not required", skills: ["Risk-taking", "Leadership", "Resilience", "Sales"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Independent", "Confident", "Resilient"], workEnvironment: "Varies", growthRate: 10 },

  // ---- Healthcare (8) ----
  { id: "registered-nurse", name: "Registered Nurse", category: "healthcare", description: "Provides direct patient care and supports treatment plans.", averageSalary: { min: 60000, max: 110000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Empathy", "Attention to detail", "Communication", "Stamina"], futureDemand: "Very High", automationRisk: "Low", typicalPersonality: ["Empathetic", "Resilient", "Attentive"], workEnvironment: "Hospital / Clinic", growthRate: 20 },
  { id: "physician", name: "Physician (General Practitioner)", category: "healthcare", description: "Diagnoses and treats patients across a wide range of conditions.", averageSalary: { min: 150000, max: 260000, currency: USD }, requiredDegree: "Doctorate", skills: ["Diagnosis", "Communication", "Empathy", "Decision making"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Empathetic", "Analytical", "Calm under pressure"], workEnvironment: "Hospital / Clinic", growthRate: 12 },
  { id: "physiotherapist", name: "Physiotherapist", category: "healthcare", description: "Helps patients recover movement and manage physical pain.", averageSalary: { min: 60000, max: 105000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Anatomy knowledge", "Empathy", "Communication", "Patience"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Patient", "Empathetic", "Practical"], workEnvironment: "Clinic / Hospital", growthRate: 17 },
  { id: "pharmacist", name: "Pharmacist", category: "healthcare", description: "Dispenses medication and advises on safe drug use.", averageSalary: { min: 100000, max: 140000, currency: USD }, requiredDegree: "Doctorate", skills: ["Attention to detail", "Chemistry knowledge", "Communication", "Accuracy"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Precise", "Reliable", "Communicative"], workEnvironment: "Pharmacy / Hospital", growthRate: 5 },
  { id: "medical-lab-tech", name: "Medical Laboratory Technician", category: "healthcare", description: "Performs diagnostic tests on patient samples.", averageSalary: { min: 45000, max: 75000, currency: USD }, requiredDegree: "Associate Degree", skills: ["Attention to detail", "Lab techniques", "Accuracy", "Organization"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Meticulous", "Methodical", "Patient"], workEnvironment: "Laboratory", growthRate: 13 },
  { id: "occupational-therapist", name: "Occupational Therapist", category: "healthcare", description: "Helps patients regain skills for daily living and work.", averageSalary: { min: 65000, max: 110000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Empathy", "Creativity", "Patience", "Problem solving"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Empathetic", "Patient", "Creative"], workEnvironment: "Clinic / Home visits", growthRate: 16 },
  { id: "paramedic", name: "Paramedic", category: "healthcare", description: "Provides emergency medical care and transport.", averageSalary: { min: 40000, max: 75000, currency: USD }, requiredDegree: "Associate Degree", skills: ["Quick thinking", "Calm under pressure", "Physical stamina", "Teamwork"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Calm under pressure", "Decisive", "Resilient"], workEnvironment: "Field / Ambulance", growthRate: 11 },
  { id: "dietitian", name: "Dietitian / Nutritionist", category: "healthcare", description: "Advises clients on nutrition and healthy eating plans.", averageSalary: { min: 50000, max: 85000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Nutrition knowledge", "Communication", "Empathy", "Planning"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Empathetic", "Organized", "Communicative"], workEnvironment: "Clinic / Private practice", growthRate: 9 },

  // ---- Engineering (7) ----
  { id: "civil-engineer", name: "Civil Engineer", category: "engineering", description: "Designs and oversees construction of infrastructure projects.", averageSalary: { min: 65000, max: 125000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Mathematics", "Design", "Problem solving", "Project management"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Practical", "Detail-oriented"], workEnvironment: "Office / Site visits", growthRate: 8 },
  { id: "mechanical-engineer", name: "Mechanical Engineer", category: "engineering", description: "Designs and tests mechanical systems and devices.", averageSalary: { min: 68000, max: 130000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Mathematics", "Design", "Problem solving", "CAD software"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Hands-on", "Curious"], workEnvironment: "Office / Workshop", growthRate: 7 },
  { id: "electrical-engineer", name: "Electrical Engineer", category: "engineering", description: "Designs electrical systems, circuits, and equipment.", averageSalary: { min: 70000, max: 135000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Mathematics", "Circuit design", "Problem solving", "Precision"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Analytical", "Precise", "Curious"], workEnvironment: "Office / Lab", growthRate: 9 },
  { id: "chemical-engineer", name: "Chemical Engineer", category: "engineering", description: "Designs processes for producing chemicals, fuel, and materials.", averageSalary: { min: 75000, max: 140000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Chemistry", "Mathematics", "Problem solving", "Safety awareness"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Careful", "Methodical"], workEnvironment: "Plant / Office", growthRate: 6 },
  { id: "aerospace-engineer", name: "Aerospace Engineer", category: "engineering", description: "Designs aircraft, spacecraft, and related systems.", averageSalary: { min: 80000, max: 150000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Mathematics", "Physics", "Design", "Precision"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Meticulous", "Curious"], workEnvironment: "Office / Lab", growthRate: 8 },
  { id: "environmental-engineer", name: "Environmental Engineer", category: "engineering", description: "Develops solutions for environmental protection and sustainability.", averageSalary: { min: 65000, max: 120000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Science knowledge", "Problem solving", "Analysis", "Communication"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Analytical", "Purpose-driven", "Practical"], workEnvironment: "Office / Field", growthRate: 15 },
  { id: "biomedical-engineer", name: "Biomedical Engineer", category: "engineering", description: "Designs medical devices and equipment.", averageSalary: { min: 70000, max: 135000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Biology", "Engineering design", "Problem solving", "Precision"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Analytical", "Curious", "Precise"], workEnvironment: "Lab / Office", growthRate: 14 },

  // ---- Science (7) ----
  { id: "research-scientist", name: "Research Scientist", category: "science", description: "Conducts original research to advance scientific knowledge.", averageSalary: { min: 65000, max: 130000, currency: USD }, requiredDegree: "Doctorate", skills: ["Research", "Critical thinking", "Writing", "Patience"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Curious", "Methodical", "Persistent"], workEnvironment: "Laboratory / University", growthRate: 8 },
  { id: "biologist", name: "Biologist", category: "science", description: "Studies living organisms and their ecosystems.", averageSalary: { min: 55000, max: 105000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Observation", "Research", "Analysis", "Patience"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Curious", "Patient", "Observant"], workEnvironment: "Lab / Field", growthRate: 7 },
  { id: "chemist", name: "Chemist", category: "science", description: "Studies substances and develops new materials or compounds.", averageSalary: { min: 55000, max: 110000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Chemistry", "Precision", "Analysis", "Lab safety"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Precise", "Analytical", "Curious"], workEnvironment: "Laboratory", growthRate: 6 },
  { id: "physicist", name: "Physicist", category: "science", description: "Studies matter, energy, and the fundamental laws of nature.", averageSalary: { min: 70000, max: 140000, currency: USD }, requiredDegree: "Doctorate", skills: ["Mathematics", "Analysis", "Research", "Abstract thinking"], futureDemand: "Low", automationRisk: "Low", typicalPersonality: ["Analytical", "Curious", "Abstract thinker"], workEnvironment: "Lab / University", growthRate: 5 },
  { id: "environmental-scientist", name: "Environmental Scientist", category: "science", description: "Studies environmental problems and develops solutions.", averageSalary: { min: 55000, max: 105000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Research", "Field work", "Analysis", "Communication"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Purpose-driven", "Analytical", "Practical"], workEnvironment: "Field / Office", growthRate: 12 },
  { id: "marine-biologist", name: "Marine Biologist", category: "science", description: "Studies ocean life and marine ecosystems.", averageSalary: { min: 50000, max: 100000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Research", "Observation", "Diving/fieldwork", "Patience"], futureDemand: "Low", automationRisk: "Low", typicalPersonality: ["Curious", "Adventurous", "Patient"], workEnvironment: "Field / Lab", growthRate: 6 },
  { id: "astronomer", name: "Astronomer", category: "science", description: "Studies celestial objects, space, and the universe.", averageSalary: { min: 65000, max: 135000, currency: USD }, requiredDegree: "Doctorate", skills: ["Mathematics", "Research", "Data analysis", "Patience"], futureDemand: "Low", automationRisk: "Low", typicalPersonality: ["Curious", "Analytical", "Patient"], workEnvironment: "Observatory / University", growthRate: 4 },

  // ---- Education (7) ----
  { id: "primary-teacher", name: "Primary School Teacher", category: "education", description: "Teaches foundational academic and social skills to young children.", averageSalary: { min: 40000, max: 70000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Patience", "Communication", "Creativity", "Classroom management"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Patient", "Nurturing", "Energetic"], workEnvironment: "Classroom", growthRate: 5 },
  { id: "secondary-teacher", name: "Secondary School Teacher", category: "education", description: "Teaches subject-specific curriculum to teenage students.", averageSalary: { min: 42000, max: 75000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Subject expertise", "Communication", "Patience", "Classroom management"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Patient", "Knowledgeable", "Engaging"], workEnvironment: "Classroom", growthRate: 4 },
  { id: "special-ed-teacher", name: "Special Education Teacher", category: "education", description: "Supports students with diverse learning needs.", averageSalary: { min: 42000, max: 75000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Patience", "Empathy", "Adaptability", "Communication"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Patient", "Empathetic", "Resilient"], workEnvironment: "Classroom", growthRate: 8 },
  { id: "school-counselor", name: "School Counselor", category: "education", description: "Supports students' academic, social, and emotional wellbeing.", averageSalary: { min: 45000, max: 80000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Empathy", "Listening", "Communication", "Problem solving"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Empathetic", "Calm", "Supportive"], workEnvironment: "School office", growthRate: 9 },
  { id: "university-lecturer", name: "University Lecturer", category: "education", description: "Teaches and researches at the tertiary education level.", averageSalary: { min: 60000, max: 130000, currency: USD }, requiredDegree: "Doctorate", skills: ["Subject expertise", "Communication", "Research", "Writing"], futureDemand: "Low", automationRisk: "Low", typicalPersonality: ["Knowledgeable", "Curious", "Articulate"], workEnvironment: "University", growthRate: 3 },
  { id: "curriculum-developer", name: "Curriculum Developer", category: "education", description: "Designs educational content and learning programs.", averageSalary: { min: 55000, max: 95000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Instructional design", "Writing", "Creativity", "Organization"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Organized", "Creative", "Detail-oriented"], workEnvironment: "Office / Remote", growthRate: 6 },
  { id: "early-childhood-educator", name: "Early Childhood Educator", category: "education", description: "Supports early development and learning in young children.", averageSalary: { min: 35000, max: 60000, currency: USD }, requiredDegree: "Associate Degree", skills: ["Patience", "Nurturing", "Creativity", "Observation"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Nurturing", "Patient", "Energetic"], workEnvironment: "Classroom / Daycare", growthRate: 6 },

  // ---- Creative (7) ----
  { id: "graphic-designer", name: "Graphic Designer", category: "creative", description: "Creates visual content for branding, marketing, and media.", averageSalary: { min: 45000, max: 85000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Design", "Creativity", "Software proficiency", "Communication"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Creative", "Detail-oriented", "Independent"], workEnvironment: "Studio / Remote", growthRate: 5 },
  { id: "video-editor", name: "Film/Video Editor", category: "creative", description: "Edits raw footage into a finished, polished production.", averageSalary: { min: 42000, max: 90000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Editing software", "Storytelling", "Attention to detail", "Creativity"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Creative", "Patient", "Detail-oriented"], workEnvironment: "Studio / Remote", growthRate: 8 },
  { id: "photographer", name: "Photographer", category: "creative", description: "Captures images for commercial, artistic, or editorial purposes.", averageSalary: { min: 35000, max: 80000, currency: USD }, requiredDegree: "Not required", skills: ["Technical skill", "Creativity", "Composition", "Communication"], futureDemand: "Low", automationRisk: "Moderate", typicalPersonality: ["Creative", "Observant", "Independent"], workEnvironment: "Studio / Field", growthRate: 3 },
  { id: "animator", name: "Animator", category: "creative", description: "Creates moving images and characters for film, games, or media.", averageSalary: { min: 50000, max: 100000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Animation software", "Creativity", "Drawing", "Patience"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Creative", "Patient", "Detail-oriented"], workEnvironment: "Studio / Remote", growthRate: 12 },
  { id: "interior-designer", name: "Interior Designer", category: "creative", description: "Designs functional and aesthetically pleasing indoor spaces.", averageSalary: { min: 45000, max: 90000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Design", "Spatial awareness", "Communication", "Creativity"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Creative", "Practical", "Communicative"], workEnvironment: "Studio / Site visits", growthRate: 6 },
  { id: "fashion-designer", name: "Fashion Designer", category: "creative", description: "Designs clothing and accessories.", averageSalary: { min: 40000, max: 95000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Design", "Sketching", "Creativity", "Trend awareness"], futureDemand: "Low", automationRisk: "Moderate", typicalPersonality: ["Creative", "Independent", "Trend-aware"], workEnvironment: "Studio", growthRate: 1 },
  { id: "content-creator", name: "Content Creator / Influencer", category: "creative", description: "Produces original digital content across social platforms.", averageSalary: { min: 25000, max: 150000, currency: USD }, requiredDegree: "Not required", skills: ["Creativity", "Communication", "Consistency", "Editing"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Creative", "Outgoing", "Resilient"], workEnvironment: "Remote / Studio", growthRate: 20 },

  // ---- Finance (7) ----
  { id: "financial-analyst", name: "Financial Analyst", category: "finance", description: "Evaluates financial data to guide investment and business decisions.", averageSalary: { min: 60000, max: 120000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analysis", "Mathematics", "Attention to detail", "Communication"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Analytical", "Precise", "Confident"], workEnvironment: "Office", growthRate: 9 },
  { id: "accountant", name: "Accountant", category: "finance", description: "Manages financial records, reporting, and compliance.", averageSalary: { min: 50000, max: 95000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Accuracy", "Organization", "Mathematics", "Ethics"], futureDemand: "Moderate", automationRisk: "High", typicalPersonality: ["Organized", "Precise", "Reliable"], workEnvironment: "Office", growthRate: 4 },
  { id: "investment-banker", name: "Investment Banker", category: "finance", description: "Advises on capital raising, mergers, and financial transactions.", averageSalary: { min: 90000, max: 220000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analysis", "Negotiation", "Stamina", "Confidence"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Confident", "Ambitious", "Analytical"], workEnvironment: "Office", growthRate: 7 },
  { id: "actuary", name: "Actuary", category: "finance", description: "Uses statistics to assess and manage financial risk.", averageSalary: { min: 75000, max: 150000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Mathematics", "Statistics", "Analysis", "Precision"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Analytical", "Precise", "Methodical"], workEnvironment: "Office", growthRate: 21 },
  { id: "financial-planner", name: "Financial Planner", category: "finance", description: "Helps individuals plan savings, investments, and retirement.", averageSalary: { min: 55000, max: 120000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Communication", "Analysis", "Trustworthiness", "Empathy"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Trustworthy", "Communicative", "Analytical"], workEnvironment: "Office", growthRate: 15 },
  { id: "auditor", name: "Auditor", category: "finance", description: "Reviews financial records to ensure accuracy and compliance.", averageSalary: { min: 55000, max: 100000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Attention to detail", "Ethics", "Analysis", "Communication"], futureDemand: "Moderate", automationRisk: "High", typicalPersonality: ["Meticulous", "Ethical", "Methodical"], workEnvironment: "Office", growthRate: 5 },
  { id: "insurance-underwriter", name: "Insurance Underwriter", category: "finance", description: "Assesses risk to determine insurance policy terms.", averageSalary: { min: 55000, max: 100000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analysis", "Risk assessment", "Attention to detail", "Decision making"], futureDemand: "Low", automationRisk: "High", typicalPersonality: ["Analytical", "Cautious", "Methodical"], workEnvironment: "Office", growthRate: -3 },

  // ---- Law (7) ----
  { id: "lawyer", name: "Lawyer / Solicitor", category: "law", description: "Advises and represents clients on legal matters.", averageSalary: { min: 70000, max: 180000, currency: USD }, requiredDegree: "Doctorate", skills: ["Argumentation", "Research", "Writing", "Attention to detail"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Articulate", "Confident"], workEnvironment: "Office / Courtroom", growthRate: 8 },
  { id: "paralegal", name: "Paralegal", category: "law", description: "Supports lawyers with research, drafting, and case preparation.", averageSalary: { min: 40000, max: 75000, currency: USD }, requiredDegree: "Associate Degree", skills: ["Research", "Organization", "Writing", "Attention to detail"], futureDemand: "Moderate", automationRisk: "High", typicalPersonality: ["Organized", "Detail-oriented", "Reliable"], workEnvironment: "Office", growthRate: 6 },
  { id: "judge", name: "Judge", category: "law", description: "Presides over legal proceedings and renders rulings.", averageSalary: { min: 120000, max: 220000, currency: USD }, requiredDegree: "Doctorate", skills: ["Impartiality", "Legal knowledge", "Decision making", "Communication"], futureDemand: "Low", automationRisk: "Low", typicalPersonality: ["Impartial", "Wise", "Confident"], workEnvironment: "Courtroom", growthRate: 3 },
  { id: "legal-consultant", name: "Legal Consultant", category: "law", description: "Provides specialized legal advice to organizations.", averageSalary: { min: 75000, max: 160000, currency: USD }, requiredDegree: "Doctorate", skills: ["Legal knowledge", "Analysis", "Communication", "Research"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Articulate", "Trustworthy"], workEnvironment: "Office", growthRate: 6 },
  { id: "corporate-counsel", name: "Corporate Counsel", category: "law", description: "Provides in-house legal guidance to a business.", averageSalary: { min: 90000, max: 190000, currency: USD }, requiredDegree: "Doctorate", skills: ["Legal knowledge", "Negotiation", "Risk assessment", "Communication"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Diplomatic", "Confident"], workEnvironment: "Office", growthRate: 7 },
  { id: "criminal-prosecutor", name: "Criminal Prosecutor", category: "law", description: "Represents the state in criminal proceedings.", averageSalary: { min: 65000, max: 140000, currency: USD }, requiredDegree: "Doctorate", skills: ["Argumentation", "Research", "Confidence", "Ethics"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Confident", "Principled", "Resilient"], workEnvironment: "Courtroom / Office", growthRate: 5 },
  { id: "mediator", name: "Mediator", category: "law", description: "Facilitates resolution between disputing parties.", averageSalary: { min: 55000, max: 110000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Communication", "Neutrality", "Empathy", "Problem solving"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Calm", "Diplomatic", "Empathetic"], workEnvironment: "Office", growthRate: 8 },

  // ---- Trades (7) ----
  { id: "electrician", name: "Electrician", category: "trades", description: "Installs and maintains electrical systems and wiring.", averageSalary: { min: 45000, max: 90000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Technical skill", "Safety awareness", "Problem solving", "Precision"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Hands-on", "Practical", "Careful"], workEnvironment: "On-site", growthRate: 11 },
  { id: "plumber", name: "Plumber", category: "trades", description: "Installs and repairs piping and water systems.", averageSalary: { min: 45000, max: 90000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Technical skill", "Problem solving", "Physical stamina", "Precision"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Hands-on", "Practical", "Resourceful"], workEnvironment: "On-site", growthRate: 9 },
  { id: "carpenter", name: "Carpenter", category: "trades", description: "Builds and repairs structures and fixtures made of wood.", averageSalary: { min: 40000, max: 80000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Craftsmanship", "Precision", "Physical stamina", "Problem solving"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Hands-on", "Patient", "Practical"], workEnvironment: "On-site / Workshop", growthRate: 6 },
  { id: "auto-technician", name: "Automotive Technician", category: "trades", description: "Diagnoses and repairs vehicles.", averageSalary: { min: 40000, max: 75000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Technical skill", "Problem solving", "Precision", "Mechanical aptitude"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Hands-on", "Practical", "Curious"], workEnvironment: "Workshop", growthRate: 5 },
  { id: "hvac-technician", name: "HVAC Technician", category: "trades", description: "Installs and maintains heating, ventilation, and cooling systems.", averageSalary: { min: 45000, max: 85000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Technical skill", "Problem solving", "Safety awareness", "Precision"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Hands-on", "Practical", "Reliable"], workEnvironment: "On-site", growthRate: 13 },
  { id: "welder", name: "Welder", category: "trades", description: "Joins metal parts using specialized welding techniques.", averageSalary: { min: 40000, max: 80000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Precision", "Technical skill", "Safety awareness", "Physical stamina"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Hands-on", "Focused", "Careful"], workEnvironment: "Workshop / Site", growthRate: 4 },
  { id: "construction-manager", name: "Construction Manager", category: "trades", description: "Oversees construction projects from planning to completion.", averageSalary: { min: 65000, max: 130000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Leadership", "Organization", "Problem solving", "Communication"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Organized", "Decisive", "Practical"], workEnvironment: "On-site / Office", growthRate: 8 },

  // ---- Government (7) ----
  { id: "policy-analyst", name: "Policy Analyst", category: "government", description: "Researches and evaluates public policy options.", averageSalary: { min: 55000, max: 105000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Research", "Analysis", "Writing", "Critical thinking"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Purpose-driven", "Articulate"], workEnvironment: "Office", growthRate: 6 },
  { id: "diplomat", name: "Diplomat / Foreign Service Officer", category: "government", description: "Represents national interests in international relations.", averageSalary: { min: 60000, max: 130000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Communication", "Cultural awareness", "Negotiation", "Adaptability"], futureDemand: "Low", automationRisk: "Low", typicalPersonality: ["Diplomatic", "Adaptable", "Confident"], workEnvironment: "Office / International travel", growthRate: 2 },
  { id: "urban-planner", name: "Urban Planner", category: "government", description: "Designs land use and development plans for communities.", averageSalary: { min: 55000, max: 100000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Design", "Analysis", "Communication", "Problem solving"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Purpose-driven", "Creative"], workEnvironment: "Office", growthRate: 7 },
  { id: "public-health-official", name: "Public Health Official", category: "government", description: "Develops and implements public health policy and programs.", averageSalary: { min: 60000, max: 120000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Analysis", "Communication", "Leadership", "Research"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Purpose-driven", "Analytical", "Communicative"], workEnvironment: "Office / Field", growthRate: 12 },
  { id: "civil-servant", name: "Civil Servant", category: "government", description: "Administers government programs and public services.", averageSalary: { min: 45000, max: 90000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Organization", "Communication", "Ethics", "Reliability"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Reliable", "Organized", "Principled"], workEnvironment: "Office", growthRate: 3 },
  { id: "intelligence-analyst", name: "Intelligence Analyst", category: "government", description: "Analyzes information to support national security decisions.", averageSalary: { min: 65000, max: 130000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analysis", "Research", "Attention to detail", "Discretion"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Discreet", "Meticulous"], workEnvironment: "Office", growthRate: 6 },
  { id: "military-officer", name: "Military Officer", category: "government", description: "Leads and manages military personnel and operations.", averageSalary: { min: 50000, max: 120000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Leadership", "Discipline", "Decision making", "Physical fitness"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Disciplined", "Decisive", "Resilient"], workEnvironment: "Varies", growthRate: 2 },

  // ---- Sports (7) ----
  { id: "professional-athlete", name: "Professional Athlete", category: "sports", description: "Competes professionally in a chosen sport.", averageSalary: { min: 30000, max: 500000, currency: USD }, requiredDegree: "Not required", skills: ["Physical fitness", "Discipline", "Resilience", "Competitiveness"], futureDemand: "Low", automationRisk: "Low", typicalPersonality: ["Disciplined", "Competitive", "Resilient"], workEnvironment: "Field / Court / Travel", growthRate: 2 },
  { id: "sports-coach", name: "Sports Coach", category: "sports", description: "Trains and mentors athletes to improve performance.", averageSalary: { min: 35000, max: 90000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Leadership", "Communication", "Motivation", "Sport knowledge"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Motivating", "Patient", "Energetic"], workEnvironment: "Field / Gym", growthRate: 8 },
  { id: "sports-physiotherapist", name: "Sports Physiotherapist", category: "sports", description: "Treats and prevents sports-related injuries.", averageSalary: { min: 55000, max: 100000, currency: USD }, requiredDegree: "Master's Degree", skills: ["Anatomy knowledge", "Empathy", "Precision", "Communication"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Empathetic", "Practical", "Attentive"], workEnvironment: "Clinic / Field", growthRate: 10 },
  { id: "sports-nutritionist", name: "Sports Nutritionist", category: "sports", description: "Designs nutrition plans to optimize athletic performance.", averageSalary: { min: 45000, max: 85000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Nutrition knowledge", "Communication", "Analysis", "Empathy"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Analytical", "Communicative", "Purpose-driven"], workEnvironment: "Clinic / Field", growthRate: 9 },
  { id: "personal-trainer", name: "Personal Trainer", category: "sports", description: "Guides individuals through fitness and exercise programs.", averageSalary: { min: 35000, max: 75000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Motivation", "Fitness knowledge", "Communication", "Energy"], futureDemand: "High", automationRisk: "Low", typicalPersonality: ["Energetic", "Motivating", "Outgoing"], workEnvironment: "Gym", growthRate: 14 },
  { id: "sports-journalist", name: "Sports Journalist", category: "sports", description: "Reports and writes on sporting events and athletes.", averageSalary: { min: 35000, max: 75000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Writing", "Research", "Communication", "Sport knowledge"], futureDemand: "Low", automationRisk: "Moderate", typicalPersonality: ["Curious", "Articulate", "Passionate"], workEnvironment: "Field / Remote", growthRate: 2 },
  { id: "athletic-director", name: "Athletic Director", category: "sports", description: "Manages sports programs for a school or organization.", averageSalary: { min: 55000, max: 110000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Leadership", "Organization", "Communication", "Budgeting"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Organized", "Decisive", "Leadership-oriented"], workEnvironment: "Office / Field", growthRate: 5 },

  // ---- Hospitality (7) ----
  { id: "hotel-manager", name: "Hotel Manager", category: "hospitality", description: "Oversees daily operations of a hotel or resort.", averageSalary: { min: 50000, max: 100000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Leadership", "Organization", "Communication", "Customer service"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Organized", "Outgoing", "Diplomatic"], workEnvironment: "Hotel", growthRate: 6 },
  { id: "chef", name: "Chef", category: "hospitality", description: "Plans menus and prepares food in a professional kitchen.", averageSalary: { min: 40000, max: 90000, currency: USD }, requiredDegree: "Trade Certification", skills: ["Culinary skill", "Creativity", "Time management", "Leadership"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Creative", "Energetic", "Disciplined"], workEnvironment: "Kitchen", growthRate: 7 },
  { id: "event-planner", name: "Event Planner", category: "hospitality", description: "Organizes and coordinates events for clients.", averageSalary: { min: 40000, max: 85000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Organization", "Creativity", "Communication", "Problem solving"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Organized", "Creative", "Sociable"], workEnvironment: "Office / On-site", growthRate: 9 },
  { id: "travel-agent", name: "Travel Agent", category: "hospitality", description: "Plans and books travel arrangements for clients.", averageSalary: { min: 35000, max: 65000, currency: USD }, requiredDegree: "Not required", skills: ["Organization", "Communication", "Research", "Customer service"], futureDemand: "Low", automationRisk: "High", typicalPersonality: ["Sociable", "Organized", "Detail-oriented"], workEnvironment: "Office / Remote", growthRate: -5 },
  { id: "restaurant-manager", name: "Restaurant Manager", category: "hospitality", description: "Manages daily restaurant operations and staff.", averageSalary: { min: 42000, max: 80000, currency: USD }, requiredDegree: "Not required", skills: ["Leadership", "Organization", "Customer service", "Multitasking"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Energetic", "Organized", "Resilient"], workEnvironment: "Restaurant", growthRate: 4 },
  { id: "flight-attendant", name: "Flight Attendant", category: "hospitality", description: "Ensures passenger safety and comfort during flights.", averageSalary: { min: 40000, max: 75000, currency: USD }, requiredDegree: "Not required", skills: ["Customer service", "Calm under pressure", "Communication", "Adaptability"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Outgoing", "Calm", "Adaptable"], workEnvironment: "Aircraft / Travel", growthRate: 6 },
  { id: "tour-guide", name: "Tour Guide", category: "hospitality", description: "Leads and informs groups during tours and excursions.", averageSalary: { min: 30000, max: 60000, currency: USD }, requiredDegree: "Not required", skills: ["Communication", "Knowledge", "Enthusiasm", "Adaptability"], futureDemand: "Low", automationRisk: "Moderate", typicalPersonality: ["Outgoing", "Knowledgeable", "Energetic"], workEnvironment: "Field / Travel", growthRate: 3 },

  // ---- Marketing (7) ----
  { id: "marketing-manager", name: "Marketing Manager", category: "marketing", description: "Develops and leads marketing strategy and campaigns.", averageSalary: { min: 65000, max: 130000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Strategic thinking", "Communication", "Leadership", "Analysis"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Strategic", "Creative", "Confident"], workEnvironment: "Office / Remote", growthRate: 10 },
  { id: "digital-marketing-specialist", name: "Digital Marketing Specialist", category: "marketing", description: "Executes online marketing campaigns across digital channels.", averageSalary: { min: 50000, max: 100000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analytics", "Creativity", "Communication", "Adaptability"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Analytical", "Creative", "Adaptable"], workEnvironment: "Office / Remote", growthRate: 16 },
  { id: "brand-strategist", name: "Brand Strategist", category: "marketing", description: "Shapes brand identity and positioning strategy.", averageSalary: { min: 60000, max: 120000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Strategic thinking", "Creativity", "Research", "Communication"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Strategic", "Creative", "Articulate"], workEnvironment: "Office / Remote", growthRate: 8 },
  { id: "seo-specialist", name: "SEO Specialist", category: "marketing", description: "Optimizes web content to improve search engine rankings.", averageSalary: { min: 45000, max: 90000, currency: USD }, requiredDegree: "Not required", skills: ["Analytics", "Research", "Technical skill", "Writing"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Analytical", "Persistent", "Detail-oriented"], workEnvironment: "Office / Remote", growthRate: 12 },
  { id: "social-media-manager", name: "Social Media Manager", category: "marketing", description: "Manages brand presence and engagement across social platforms.", averageSalary: { min: 42000, max: 85000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Creativity", "Communication", "Trend awareness", "Consistency"], futureDemand: "High", automationRisk: "Moderate", typicalPersonality: ["Creative", "Outgoing", "Adaptable"], workEnvironment: "Office / Remote", growthRate: 15 },
  { id: "market-research-analyst", name: "Market Research Analyst", category: "marketing", description: "Studies market conditions to guide product and marketing decisions.", averageSalary: { min: 50000, max: 100000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Analysis", "Research", "Statistics", "Communication"], futureDemand: "Moderate", automationRisk: "Moderate", typicalPersonality: ["Analytical", "Curious", "Methodical"], workEnvironment: "Office / Remote", growthRate: 13 },
  { id: "pr-specialist", name: "Public Relations Specialist", category: "marketing", description: "Manages public image and media relationships for organizations.", averageSalary: { min: 45000, max: 95000, currency: USD }, requiredDegree: "Bachelor's Degree", skills: ["Communication", "Writing", "Relationship building", "Crisis management"], futureDemand: "Moderate", automationRisk: "Low", typicalPersonality: ["Articulate", "Diplomatic", "Confident"], workEnvironment: "Office", growthRate: 7 },
];

export function getCareerById(id: string): CareerRecord | undefined {
  return CAREER_DATA.find((c) => c.id === id);
}

export function getCareersByCategory(category: string): CareerRecord[] {
  return CAREER_DATA.filter((c) => c.category === category);
}